python:
  version: "3.10.6"

databases:
  - name: ketema_farm  
    plan: free
    engine: postgresql
    version: 16

services:
  - type: web
    name: django-app
    runtime: python
    rootDirectory: backend/  # ← Key addition
    buildCommand: |
      pip install -r ../requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn your_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ketema_farm
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
