python:
  version: "3.10.6"

databases:
  - name: ketema_farm  
    plan: free
    engine: postgresql
    version: 16

services:
  - type: web
    name: django-app
    runtime: python
    port: 10000  # Critical fix
    protocol: tcp
    rootDirectory: backend/
    buildCommand: |
      cd backend && \
      pip install -r requirements.txt && \
      python manage.py collectstatic --noinput && \
      python manage.py migrate
    startCommand: |
      cd backend && \
      gunicorn your_project.wsgi:application \
        --bind 0.0.0.0:10000 \  # Must match port
        --workers=2 \
        --timeout 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ketema_farm
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
