# Generated by Django 5.1.2 on 2025-05-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(choices=[('ADDIS_ABABA', 'Addis Ababa'), ('ADAMA', 'Adama'), ('BAHIR_DAR', 'Bahir Dar'), ('GONDAR', 'Gondar'), ('MEKELLE', 'Mekelle'), ('DIRE_DAWA', 'Dire Dawa'), ('HAWASSA', 'Hawassa'), ('JIMMA', 'Jimma'), ('HARAR', 'Harar'), ('ASSOSA', 'Assosa')], default='ADDIS_ABABA', max_length=20),
            preserve_default=False,
        ),
    ]

#show posts and lands in profile  and DELETE